version: '3.9'
services:
  react-frontend:
    build:
      context: ../devops-fe
    container_name: react-frontend-container
    environment:
      - REACT_APP_BACKENDHOST=localhost:4400
    ports:
      - "3000:3000"
    depends_on:
      - node-backend
    networks:
      - app-network

  # Backend: Node.js
  node-backend:
    build:
      context: .
    container_name: node-backend-container
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres-db:5432/todoapp
      - JWT_SECRET=abcd
    ports:
      - "4400:4400"
    depends_on:
      - postgres-db
    networks:
      - app-network
    command: >
      sh -c "
      until nc -z postgres-db 5432; do
        echo 'Waiting for database...';
        sleep 2;
      done;
      echo 'Database is ready!';
      npx prisma migrate dev --name init && node server.js
      "

  # Database: PostgreSQL
  postgres-db:
    image: postgres:latest
    container_name: postgres-db-container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todoapp
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
