name: Build on push
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Dockerize the app
        run: |
          docker build -t backend .
          docker run backend
      - name: check if the container is running
        run: |
          docker ps
      - name: Get the output of docker images and docker ps -a
        run: |
          docker images
          docker ps -a